### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by jonsneyers** [libjxl/bench#2]
- [ ] allow writing icc in the wrap (if possible without modifying libjxl/conformance, let's see
- [ ] style html report more, and e.g. be more forgiving with the limits
- [ ] include error messages, which are present in json, also in html report in some way
- [x] write a script/instructions that does "everything": (1) building jxl-oxide, libjxl, jxlatte, (2) running the script to dump the jsons (3) update the jsons in a way that can then be displayed via e.g. https://libjxl.github.io/bench or something and 
- [ ] possibly make it a github workflow
- [ ] (strech goal): include the images written during decoding, so that one can click on them and compare them
- [x] correct usage `jxlatte`, avoid `jxl-latte` etc..
- [ ] add https://github.com/lifthrasiir/j40 decoder
- [ ] ...?

_Originally posted by @mo271 in https://github.com/libjxl/bench/issues/1#issuecomment-1602709357_

**Comment by mo271** [comment]
replaced by individual issues
